# Generated by Django 3.0.5 on 2020-04-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_tree',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='skilltree',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='skilltree',
            name='restriction',
            field=models.ManyToManyField(related_name='_skilltree_restriction_+', to='main.SkillTree'),
        ),
        migrations.CreateModel(
            name='SkillTreeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.ManyToManyField(related_name='_skilltreeskill_requirements_+', to='main.SkillTreeSkill')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Skill')),
                ('skillTree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SkillTree')),
            ],
        ),
    ]
