# Generated by Django 3.0.5 on 2020-04-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200429_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltreeskill',
            name='skillTree',
        ),
        migrations.AddField(
            model_name='skilltree',
            name='skill',
            field=models.ManyToManyField(blank=True, through='main.SkillTreeSkill', to='main.Skill'),
        ),
        migrations.AddField(
            model_name='skilltreeskill',
            name='SkillTree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SkillTree'),
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='restriction',
            field=models.ManyToManyField(blank=True, related_name='_skilltree_restriction_+', to='main.SkillTree'),
        ),
    ]
