# Generated by Django 3.0.5 on 2020-05-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200429_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='currentXP',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilltree',
            name='attribut',
            field=models.CharField(blank=True, choices=[('PHY', 'Physique'), ('ESP', 'Esprit'), ('INF', 'Influence')], default='PHY', max_length=3),
        ),
        migrations.CreateModel(
            name='CharacterSkillTreeSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharacterSkillTree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CharacterSkillTree')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SkillTreeSkill')),
            ],
        ),
    ]
