# Generated by Django 3.0.5 on 2020-05-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200503_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterskilltree',
            old_name='skill_tree',
            new_name='skillTree',
        ),
        migrations.RenameField(
            model_name='skilltreeskill',
            old_name='SkillTree',
            new_name='skillTree',
        ),
        migrations.AddField(
            model_name='character',
            name='armureMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='isDead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='characterskilltree',
            name='countForHP',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='skilltreeskill',
            name='tier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='currentXP',
            field=models.IntegerField(default=5),
        ),
    ]
