# Generated by Django 3.0.5 on 2020-05-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200504_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltree',
            name='slug',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='skilltree',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
