# Generated by Django 3.0.5 on 2020-05-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200504_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(blank=True, choices=[('ARS', 'Maniement des armes simples'), ('ARC', 'Maniement des armes de combat'), ('ARG', 'Maniement des armes de guerre'), ('ARS', 'Maniement des armes de jet'), ('ARD', 'Maniement des armes à distance'), ('ALE', "Port d'armure légère"), ('ALO', "Port d'armure lourde"), ('PBO', 'Port des petits boucliers'), ('GBO', 'Port des grands boucliers')], default='ARS', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='skilltree',
            name='equipement',
            field=models.ManyToManyField(to='main.Equipement'),
        ),
    ]
