# Generated by Django 3.0.5 on 2020-05-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200504_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltreeskill',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='_skilltreeskill_requirements_+', to='main.SkillTreeSkill'),
        ),
    ]
