# Generated by Django 3.0.5 on 2020-08-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200822_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilltree',
            name='skill',
        ),
        migrations.AddField(
            model_name='skilltree',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.SkillTreeSkill'),
        ),
    ]
